---
- name: Setup vprofile Stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:

    - name: Import VPC setup output variables
      include_vars: vars/output_vars   # Import variables from the 'vars/output_vars' file.

    - name: Import vprofile setup variables
      include_vars: vars/vprostack_setup

    - name: Create vprofile ec2 key
      ec2_key:
        name: vprokey        # Name of the EC2 key pair to be created.
        region: "{{region}}"      # AWS region where the key pair will be created.
      register: vprokey_out           # Store the output of this task in the 'key_out' variable.

    - name: Save private key into file loginkey_vpro.pem
      copy:
        content: "{{vprokey_out.key.private_key}}"  # Private key generated in the previous task.
        dest: ./loginkey_vpro.pem                 # Destination path for saving the private key.
        mode: 0600                              # Set permissions on the private key file.
      when: vprokey_out.changed                     # Conditionally execute this task when the private key changes.
    
    - debug:
       var: vprokey_out

    - name: Create Security group for Load Balancer
      ec2_group:
        name: vpro-elb-SG                 # Name of the security group for Load Balancer
        description: Allow port 80 from everywhere and all ports within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"              # ID of the VPC to associate the security group with.
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 80
      register: vpro_ELB_SG_out            # Store the output of this task in 'vpro_ELB_SG_out'.

    - name: Create Security group for vprofile stack
      ec2_group:
        name: vpro-stack-SG
        description: Allow port 22 from everywhere and all ports within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"              # ID of the VPC to associate the security group with.
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{vpro_ELB_SG_out.group_id}}"
            rule_desc: allow traffic to Load Balancer on port 80

          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{BastionSGid}}"
            rule_desc: allow access from bastion host on port 22
      register: vpro_stack_SG_out            # Store the output of this task in 'vpro_stack_SG_out'.

    - name: Update Security group with its own sg id
      ec2_group:
        name: vpro-stack-SG
        description: Allow port 22 from everywhere and all ports within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"              # ID of the VPC to associate the security group with.
        purge_rules: no
        rules:
          - proto: all
            group_id: "{{vpro_stack_SG_out.group_id}}"
            rule_desc: allow traffic to within SG

    - name: Create Nginx web01
      ec2:
        key_name: vprokey
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{nginx_ami}}"         # AMI ID for the bastion host image.
        wait: yes
        wait_timeout: 300                # Maximum time [sec] to wait for instance creation.
        instance_tags:
          Name: "web01"
          Project: Vprofile
          Owner: DevOps
        exact_count: 1                   # Create exactly 1 instance.
        count_tag:
          Name: "web01"
          Project: Vprofile
          Owner: DevOps
        group_id: "{{vpro_stack_SG_out.group_id}}"  # Security group ID created in the previous task.
        vpc_subnet_id: "{{privsub1_id}}"          # ID of the public subnet to launch the instance.
      register: web01_out           # Store the output of this task in 'web01_out'.

    - name: Create Tomcat app01
      ec2:
        key_name: vprokey
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{tomcat_ami}}"         # AMI ID for the bastion host image.
        wait: yes
        wait_timeout: 300                # Maximum time [sec] to wait for instance creation.
        instance_tags:
          Name: "app01"
          Project: Vprofile
          Owner: DevOps
        exact_count: 1                   # Create exactly 1 instance.
        count_tag:
          Name: "app01"
          Project: Vprofile
          Owner: DevOps
        group_id: "{{vpro_stack_SG_out.group_id}}"  # Security group ID created in the previous task.
        vpc_subnet_id: "{{privsub1_id}}"          # ID of the public subnet to launch the
      register: app01_out           # Store the output of this task in 'app01_out'.

    - name: Create memcache mc01
      ec2:
        key_name: vprokey
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{memcache_ami}}"         # AMI ID for the bastion host image.
        wait: yes
        wait_timeout: 300                # Maximum time [sec] to wait for instance creation.
        instance_tags:
          Name: "mc01"
          Project: Vprofile
          Owner: DevOps
        exact_count: 1                   # Create exactly 1 instance.
        count_tag:
          Name: "mc01"
          Project: Vprofile
          Owner: DevOps
        group_id: "{{vpro_stack_SG_out.group_id}}"  # Security group ID created in the previous task.
        vpc_subnet_id: "{{privsub1_id}}"          # ID of the public subnet to launch the
      register: mc01_out           # Store the output of this task in 'mc01_out'.

    - name: Create RabbitMQ rmq01
      ec2:
        key_name: vprokey
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{rmq_ami}}"         # AMI ID for the bastion host image.
        wait: yes
        wait_timeout: 300                # Maximum time [sec] to wait for instance creation.
        instance_tags:
          Name: "rmq01"
          Project: Vprofile
          Owner: DevOps
        exact_count: 1                   # Create exactly 1 instance.
        count_tag:
          Name: "rmq01"
          Project: Vprofile
          Owner: DevOps
        group_id: "{{vpro_stack_SG_out.group_id}}"  # Security group ID created in the previous task.
        vpc_subnet_id: "{{privsub1_id}}"          # ID of the public subnet to launch the
      register: rmq01_out           # Store the output of this task in 'rmq01_out'

    - name: Create Mysql db01
      ec2:
        key_name: vprokey
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{mysql_ami}}"         # AMI ID for the bastion host image.
        wait: yes
        wait_timeout: 300                # Maximum time [sec] to wait for instance creation.
        instance_tags:
          Name: "db01"
          Project: Vprofile
          Owner: DevOps
        exact_count: 1                   # Create exactly 1 instance.
        count_tag:
          Name: "db01"
          Project: Vprofile
          Owner: DevOps
        group_id: "{{vpro_stack_SG_out.group_id}}"  # Security group ID created in the previous task.
        vpc_subnet_id: "{{privsub1_id}}"          # ID of the public subnet to launch the
      register: db01_out           # Store the output of this task in 'db01_out'

    - debug:
        var: db01_out.tagged_instances[0].id

    - local_action:
        module: ec2_elb_lb
        name: "vprofile-elb"
        region: "{{region}}"
        state: present
        instance_ids:
          - "{{ web01_out.tagged_instances[0].id }}"
        purge_instance_ids: true
        security_group_ids: "{{ vpro_ELB_SG_out.group_id }}"
        subnets:
          - "{{ pubsub1_id }}"
          - "{{ pubsub2_id }}"
          - "{{ pubsub3_id }}"
        listeners:
          - protocol: http # options are http, https, ssl, tcp
            load_balancer_port: 80
            instance_port: 80

    - name: Insert/Update Hosts IP & Name in file provision-stack/group_vars/hostsIP
      blockinfile:
        path: provision-stack/group_vars/hostsIP
        block: |
          web01_id: {{ web01_out.tagged_instances[0].private_ip }}
          app01_id: {{ app01_out.tagged_instances[0].private_ip }}
          rmq01_id: {{ rmq01_out.tagged_instances[0].private_ip }}
          mc01_id: {{ mc01_out.tagged_instances[0].private_ip }}
          db01_id: {{ db01_out.tagged_instances[0].private_ip }}

    - name: Copy login key to provision_stack directory
      copy:
        src: loginkey_vpro.pem
        dest: provision-stack/loginkey_vpro.pem
        mode: '0400'

    - name: Insert/Update Inventory file provision-stack/inventory-vpro
      blockinfile:
        path: provision-stack/inventory-vpro
        block: |
          web01 ansible_host={{ web01_out.tagged_instances[0].private_ip }}
          app01 ansible_host={{ app01_out.tagged_instances[0].private_ip }}
          rmq01 ansible_host={{ rmq01_out.tagged_instances[0].private_ip }}
          mc01 ansible_host={{ mc01_out.tagged_instances[0].private_ip }}
          db01 ansible_host={{ db01_out.tagged_instances[0].private_ip }}
          ctrl ansible_host=127.0.0.1 ansible_connection=local
          
          [websrvgrp]
          web01
          
          [appsrvgrp]
          app01
          
          [rmqsrvgrp]
          rmq01
          
          [mcsrvgrp]
          mc01
          
          [dbsrvgrp]
          db01
          
          [control]
          ctrl
          
          [stack_inst:children]
          websrvgrp
          appsrvgrp
          rmqsrvgrp
          mcsrvgrp
          dbsrvgrp
          
          [stack_inst:vars]
          ansible_user=ubuntu
          ansible_ssh_private_key_file=loginkey_vpro.pem
          #ansible_python_interpreter=/usr/bin/python3
          
