---
- name: Setup vprofile Stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup variables
      include_vars: vars/vpc_setup

    - name: Import VPC setup output variables
      include_vars: vars/output_vars   # Import variables from the 'vars/output_vars' file.

    - name: Import vprofile setup variables
      include_vars: vars/vprostack_setup

    - name: Create vprofile ec2 key
      ec2_key:
        name: vpro-key        # Name of the EC2 key pair to be created.
        region: "{{region}}"      # AWS region where the key pair will be created.
      register: vprokey_out           # Store the output of this task in the 'key_out' variable.

    - name: Save private key into file vpro-key.pem
      copy:
        content: "{{vprokey_out.key.private_key}}"  # Private key generated in the previous task.
        dest: ./vpro-key.pem                 # Destination path for saving the private key.
        mode: 0600                              # Set permissions on the private key file.
      when: vprokey_out.changed                     # Conditionally execute this task when the private key changes.

    - name: Create Security group for Load Balancer
      ec2_group:
        name: vpro-elb-SG                 # Name of the security group for Load Balancer
        description: Allow port 80 from everywhere and all ports within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"              # ID of the VPC to associate the security group with.
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 80
      register: vpro_ELB_SG_out            # Store the output of this task in 'BastionSG_out'.

    - name: Create Security group for vprofile stack
      ec2_group:
        name: vpro-stack-SG
        description: Allow port 22 from everywhere and all ports within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"              # ID of the VPC to associate the security group with.
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{vpro_ELB_SG_out.group_id}}"
            rule_desc: allow traffic to Load Balancer on port 80

          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{BastionSGid}}"
            rule_desc: allow access from bastion host on port 22
      register: vpro_stack_SG_out            # Store the output of this task in 'vpro_stack_SG_out'.

    - name: Update Security group with its own sg id
      ec2_group:
        name: vpro-stack-SG
        description: Allow port 22 from everywhere and all ports within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"              # ID of the VPC to associate the security group with.
        purge_rules: no
        rules:
          - proto: all
            group_id: "{{vpro_stack_SG_out.group_id}}"
            rule_desc: allow traffic to within SG

    - name: Create Nginx web01
      ec2:
        key_name: vpro-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{nginx_ami}}"         # AMI ID for the bastion host image.
        wait: yes
        wait_timeout: 300                # Maximum time [sec] to wait for instance creation.
        instance_tags:
          Name: "web01"
          Project: Vprofile
          Owner: DevOps
        exact_count: 1                   # Create exactly 1 instance.
        count_tag:
          Name: "web01"
          Project: Vprofile
          Owner: DevOps
        group_id: "{{vpro_stack_SG_out.group_id}}"  # Security group ID created in the previous task.
        vpc_subnet_id: "{{privsub1_id}}"          # ID of the public subnet to launch the instance.
      register: web01_out           # Store the output of this task in 'web01_out'.

    - name: Create Tomcat app01
      ec2:
        key_name: vpro-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{tomcat_ami}}"         # AMI ID for the bastion host image.
        wait: yes
        wait_timeout: 300                # Maximum time [sec] to wait for instance creation.
        instance_tags:
          Name: "app01"
          Project: Vprofile
          Owner: DevOps
        exact_count: 1                   # Create exactly 1 instance.
        count_tag:
          Name: "app01"
          Project: Vprofile
          Owner: DevOps
        group_id: "{{vpro_stack_SG_out.group_id}}"  # Security group ID created in the previous task.
        vpc_subnet_id: "{{privsub1_id}}"          # ID of the public subnet to launch the
      register: app01_out           # Store the output of this task in 'app01_out'.

    - name: Create memcache mc01
      ec2:
        key_name: vpro-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{memcache_ami}}"         # AMI ID for the bastion host image.
        wait: yes
        wait_timeout: 300                # Maximum time [sec] to wait for instance creation.
        instance_tags:
          Name: "mc01"
          Project: Vprofile
          Owner: DevOps
        exact_count: 1                   # Create exactly 1 instance.
        count_tag:
          Name: "mc01"
          Project: Vprofile
          Owner: DevOps
        group_id: "{{vpro_stack_SG_out.group_id}}"  # Security group ID created in the previous task.
        vpc_subnet_id: "{{privsub1_id}}"          # ID of the public subnet to launch the
      register: mc01_out           # Store the output of this task in 'mc01_out'.

    - name: Create RabbitMQ rmq01
      ec2:
        key_name: vpro-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{rmq_ami}}"         # AMI ID for the bastion host image.
        wait: yes
        wait_timeout: 300                # Maximum time [sec] to wait for instance creation.
        instance_tags:
          Name: "rmq01"
          Project: Vprofile
          Owner: DevOps
        exact_count: 1                   # Create exactly 1 instance.
        count_tag:
          Name: "rmq01"
          Project: Vprofile
          Owner: DevOps
        group_id: "{{vpro_stack_SG_out.group_id}}"  # Security group ID created in the previous task.
        vpc_subnet_id: "{{privsub1_id}}"          # ID of the public subnet to launch the
      register: rmq01_out           # Store the output of this task in 'rmq01_out'

    - name: Create Mysql db01
      ec2:
        key_name: vpro-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{mysql_ami}}"         # AMI ID for the bastion host image.
        wait: yes
        wait_timeout: 300                # Maximum time [sec] to wait for instance creation.
        instance_tags:
          Name: "db01"
          Project: Vprofile
          Owner: DevOps
        exact_count: 1                   # Create exactly 1 instance.
        count_tag:
          Name: "db01"
          Project: Vprofile
          Owner: DevOps
        group_id: "{{vpro_stack_SG_out.group_id}}"  # Security group ID created in the previous task.
        vpc_subnet_id: "{{privsub1_id}}"          # ID of the public subnet to launch the
      register: db01_out           # Store the output of this task in 'db01_out'

    - debug:
        var: db01_out